version: "3.8"
services:
  php:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: php-server
    restart: always
    ports:
      - 8080:80
    volumes:
      - ./html:/var/www/html
      - ./1redesplus:/var/www/1redesplus
      - ./2redesplus:/var/www/2redesplus
      # ./var:/var
      - ./apache2/sites-avilable:/etc/apache2/sites-avilable
volumes:
  html: {}
